import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type CategoryDocument = Category & Document;

@Schema()
export class Category {

    //@Prop({type: Types.ObjectId})
    //_id: holds an ObjectId autogenerated. Iimplicitly has "index: true".

    @Prop({ required: true, unique: true })
    name: string;

    @Prop()
    description: string;
}

export const CategorySchema = SchemaFactory.createForClass(Category);

