import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';
import { ICategory } from 'src/domain/model/category/category.interface';

export type CategoryDocument = Category & Document;

@Schema()
export class Category implements ICategory{

    //@Prop({type: Types.ObjectId})
    //_id: holds an ObjectId autogenerated. Iimplicitly has "index: true".

    @Prop({ required: true, unique: true })
    name: string;

    @Prop()
    description: string;
}

export const CategorySchema = SchemaFactory.createForClass(Category);

