import { Prop, SchemaFactory, Schema } from '@nestjs/mongoose';
import { Document, Schema as MongoSchema } from 'mongoose';
import { IProfile } from 'src/domain/model/profile/profile.interface';
import { AddressDocument } from './address.schema';

export type ProfileDocument = Profile & Document;

@Schema()
export class Profile implements IProfile {

  //_id: holds an ObjectId autogenerated. Iimplicitly has "index: true".

  @Prop({ required: true, unique: true }) // implicitly has "index: true" because is unique
  userId: string; //Auth

  @Prop()
  enable: boolean;

  @Prop({ required: true, unique: true }) // implicitly has "index: true" because is unique
  userName: string;

  @Prop({
    required: true,
    min: 6,
    max: 255
  })
  firstName: string;

  @Prop({
    required: true,
  })
  lastName: string;

  @Prop({
    unique: true,
    required: true,
    min: 6,
    max: 1024
  }) // implicitly has "index: true" because is unique
  email: string;
  
  @Prop()
  docType: string;

  @Prop()
  document: string;

  @Prop()
  telephone: string;

  @Prop()
  language: string;

  @Prop()
  addresses: AddressDocument[]

  @Prop({ required: true, default: new Date() })
  createdAt?: Date;

  @Prop({ required: true, default: new Date() })
  updatedAt?: Date;
};

export const ProfileSchema = SchemaFactory.createForClass(Profile);