import { Prop, SchemaFactory, Schema } from '@nestjs/mongoose';
import { Document, Schema as MongoSchema } from 'mongoose';

export type ProfileDocument = Profile & Document;

@Schema()
export class Profile {

  //_id: holds an ObjectId autogenerated. Iimplicitly has "index: true".

  @Prop({ required: true, unique: true }) // implicitly has "index: true" because is unique
  userId: string; //Auth

  @Prop()
  enable: boolean;

  @Prop({ required: true, unique: true }) // implicitly has "index: true" because is unique
  userName: string;

  @Prop({
    required: true,
    min: 6,
    max: 255
  })
  firstName: string;

  @Prop({
    required: true,
  })
  lastName: string;

  @Prop({
    unique: true,
    required: true,
    min: 6,
    max: 1024
  }) // implicitly has "index: true" because is unique
  email: string;
  
  @Prop()
  docType: string;

  @Prop()
  document: string;

  @Prop()
  telephone: string;

  @Prop()
  language: string;

  @Prop()
  addresses: [{
    street: { type: string }, //street with number
    department: { type: string }, //department, flat or office
    neighborhood: { type: string }, //neighborhood or commune
    city: { type: string }, //city
    state: { type: string }, //state, region or province
    country: { type: string } //country
  }]

  @Prop({ required: true, default: new Date() })
  createdAt?: Date;

  @Prop({ required: true, default: new Date() })
  updatedAt?: Date;
};

export const ProfileSchema = SchemaFactory.createForClass(Profile);