
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';
import { IBusiness } from './../domain/Business.entity';
    
export type BusinessDocument = Business & Document;
    
@Schema()
export class Business implements IBusiness{
    
//@Prop({type: Types.ObjectId})
//_id: holds an ObjectId autogenerated. Iimplicitly has "index: true".
    
@Prop({ required: true }) 
country: string; //Chile | Argentina | ...

@Prop({ required: true, unique: true }) 
taxIdNum: string;

@Prop({ required: true, unique: true }) 
socialReason: string;

@Prop({ required: true }) 
fantasyName: string;

@Prop({ required: true }) 
activity: string;

@Prop({ required: true }) 
addressLine: string;

@Prop({ required: true }) 
email: string;

@Prop({ required: true }) 
phone: string;

@Prop({ required: true, default: '' })
message: string;

}
    
export const BusinessSchema = SchemaFactory.createForClass(Business);
