export enum OrderStatus {
    INITIALIZED = 'INITIALIZED',
    UPDATED = 'UPDATED',
    CONFIRMED = 'CONFIRMED',
    PAYING = 'PAYING',
    PAID = 'PAID',
    DELIVERED = 'DELIVERED',
    EXPIRED = 'EXPIRED',
    ABORTED = 'ABORTED',
    REFUNDED = 'REFUNDED',
}